### ISSUE TITLE
How to uncomment DISABLE_NOTIFICATIONS ?

### ISSUE THREAD

**Issue by RogerSik** [alvistack/ansible-role-jira#12]
How to uncomment DISABLE_NOTIFICATIONS in bin/setenv.sh ?

**Comment by hswong3i** [comment]
Refer to the comment from https://github.com/alvistack/ansible-role-jira/blob/master/templates/opt/atlassian/jira/bin/setenv.sh.j2#L45-L47:
```
# Uncomment this setting if you want to import data without notifications
#
#DISABLE_NOTIFICATIONS=" -Datlassian.mail.senddisabled=true -Datlassian.mail.fetchdisabled=true -Datlassian.mail.popdisabled=true"
```

I guess you are trying to have a XML backup restore? In this case because it is not such often use case, I will making it as an options for `defaults/main.yml` (due to [KISS principle](https://en.wikipedia.org/wiki/KISS_principle)).

You could first deploy JIRA with my role, manually stop the instance, manually change the `DISABLE_NOTIFICATIONS`, start it again for your data import. Once completed, re-run my role to verify it as normal status ;-)

**Comment by RogerSik** [comment]
Yes but this would be a manuel step to do every time when updating the Staging System. Hoped this could be done with this role. :)

**Comment by hswong3i** [comment]
For staging setup, I usually handle with complete JIRA_HOME + JIRA_CATALINA rsync from production, then also restore DB from PostgreSQL level.

Don't always believe with Atlassian's XML backup/restore process, I only use it for:
- Migrate DB backend, e.g. from H2/MySQL to PostgreSQL/MSSQL/Oracle, or
- DB records looks dirty, so purify it with XML backup -> import to a newly installed clean system + rsync JIRA_HOME/attachements from legacy system
