### ISSUE TITLE
Issue with GC options

### ISSUE THREAD

**Issue by Alex9779** [alvistack/ansible-role-jira#3]
Hey, I am trying to use your roles, this one and the one for Confluence, but both seem to have issues with the extra options you set for the JVM all GC related stuff... Crowd and Bitbucket work fine so far. I am on Ubtuntu 18.04 machines, seems the OpenJDK does not support these options.
Are they really needed?
I think I am going to replace your 'setenv.sh' changes with the original one supplied by Atlassian and just pull in the tags for jinja...

**Comment by Alex9779** [comment]
OK I think I found my error, the problem is Java 11, so going to get 8... sorry for bothering...

**Comment by hswong3i** [comment]
Yes please refer to molecule test case as recommended setup reference.

My basic principle for Atlassian’s stuff + Java version is: upgrade to another version, e.g. from openjdk 8 to 11, once all its 6 stuffs are confirm to be supported, else keep it as is.

I have this conclusion since jdk support upgrade form 6 to 7 to 8... Don’t make it too early else just keep on fighting with some we’ll known bugs...

**Comment by hswong3i** [comment]
Fixed by https://github.com/alvistack/ansible-role-jira/commit/86df9c7f28511fe7af05da9681726b8e23b4395e
